config/routes.rb
Lab01PhotoAlbum::Application.routes.draw do
  resources :user_sessions
  match 'login', :to => 'user_sessions#new', :as => "login"
  match 'logout', :to => 'user_sessions#destroy', :as => "logout"

  resources :roles

  resources :users

  
    resources :albums do
	resources :photos
    end

  root :to => "albums#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
	
	has_many :photos
	
	validates_presence_of :title, :description
	validates_uniqueness_of :title
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

   #Method from declarative_authorization to identify access to 
   #functionality.  Uses config/authorization_rules.rb to know access rights.
   filter_resource_access

  # GET /albums
  # GET /albums.xml
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.xml
  def show
    ###Access handled through declarative_authorization's before_filter in application_controller.rb
	###@album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.xml
  def new
    ###Access handled through declarative_authorization's before_filter in application_controller.rb
    ###@album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @album }
    end
  end

  # GET /albums/1/edit
  def edit
    ###Access handled through declarative_authorization's before_filter in application_controller.rb
    ###@album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.xml
  def create
    ###Access handled through declarative_authorization's before_filter in application_controller.rb
    ###@album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        ###format.html { redirect_to(@album, :notice => 'Album was successfully created.') }
	    format.html { redirect_to(album_photos_url(@album), :notice => 'Album was successfully created.') }
        format.xml  { render :xml => @album, :status => :created, :location => @album }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.xml
  def update
    ###Access handled through declarative_authorization's before_filter in application_controller.rb
    ###@album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        ###format.html { redirect_to(@album, :notice => 'Album was successfully updated.') }
	    format.html { redirect_to(album_photos_url(@album), :notice => 'Album was successfully updated.') }
	
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @album.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.xml
  def destroy
    ###Access handled through declarative_authorization's before_filter in application_controller.rb
	###@album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to(albums_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/edit.html.erb
<h1>Editing "<%= @album.title.capitalize %>" Album</h1>

<%= render 'form' %>

<% if permitted_to? :show, @album %>
    <!-- %= link_to 'Show', album_photos_path(@album) % -->
<% end %>
<% if permitted_to? :show, @album %>
    <%= link_to 'Back to Photo Album', album_photos_path(@album) %>
<% end %>

app/views/albums/index.html.erb
<h1>Photo Albums</h1>

<p><i>Click album name to view/manage contents or <%= link_to 'Add a new photo album', new_album_path %></i></p>

<table>
<% header_row = false %>
<% @albums.each do |album| %>


  <% if !header_row %>
    <tr>
      <th>Album Title</th>
      <!-- th>Description</th -->
      <!-- th></th -->
      <!-- th></th -->
      <!-- th></th -->
      <% header_row = true %>
    </tr>
  <% end %>

  <tr>
    
    <!-- td><%= album.title %></td -->
    <td><%= link_to album.title, album_photos_path(album), { :title => album.description } %></td>
    
    <!-- td><%= album.description %></td -->
    
    <% if permitted_to? :show, album %>
    	<!-- td><%= link_to 'Show', album_photos_path(album) %></td -->
    <% end %>
    <% if permitted_to? :edit, album %>
    	<!-- td><%= link_to 'Edit', edit_album_path(album) %></td -->
    <% end %>
    <% if permitted_to? :destroy, album %>	
    	<!-- td><%= link_to 'Destroy', album, :confirm => 'Are you sure?', :method => :delete %></td -->
    <% end %>
    
  </tr>
<% end %>
</table>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<% if permitted_to? :index, @album %>
	<%= link_to 'List Albums', albums_path %>
<% end %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @album.title %>
</p>

<p>
  <b>Description:</b>
  <%= @album.description %>
</p>


<%# permitted_to? method part of declarative_authorization %>
<% if permitted_to? :edit, @album %>
	<%= link_to 'Edit', edit_album_path(@album) %> |
<% end %>
<% if permitted_to? :destroy, @album %>	
	<%= link_to 'Destroy', @album, :confirm => 'Are you sure?', :method => :delete %> |
<% end %>
<% if permitted_to? :index, @album %>
	<%= link_to 'List Albums', albums_path %>
<% end %>