config/routes.rb
Lab01PhotoAlbum::Application.routes.draw do
  resources :user_sessions
  match 'login', :to => 'user_sessions#new', :as => "login"
  match 'logout', :to => 'user_sessions#destroy', :as => "logout"

  resources :roles

  resources :users

  
    resources :albums do
	resources :photos
    end

  root :to => "albums#index"

end

app/models/role.rb
class Role < ActiveRecord::Base

  validates_uniqueness_of :name
  validates_presence_of :name, :description
  
  has_many :users
  
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

  #Method from declarative_authorization to identify access to 
  #functionality.  Uses config/authorization_rules.rb to know access rights.
  filter_resource_access

  # GET /roles
  # GET /roles.xml
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.xml
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.xml
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.xml
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to(@role, :notice => 'Role was successfully created.') }
        format.xml  { render :xml => @role, :status => :created, :location => @role }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.xml
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to(@role, :notice => 'Role was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.xml
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to(roles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> 
|<% if permitted_to? :index, @role %>
	<%= link_to 'List Roles', roles_path %>
<% end %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>

<% header_row = false %>
<% @roles.each do |role| %>
  <% if !header_row %>
	  <tr>
	      <th>Name</th>
	      <th>Description</th>
		<% if permitted_to? :show, role %>
			<th></th>
		<% end %>
		<% if permitted_to? :edit, role%>
			<th></th>
		<% end %>
		<% if permitted_to? :destroy, role %>
			<th></th>
		<% end %>
		<% header_row = true %>
	  </tr>
  <% end %>
  <tr>
    	<td><%= role.name %></td>
    	<td><%= role.description %></td>
	<% if permitted_to? :show, role %>
	   <td><%= link_to 'Show', role %></td>
	<% end %>
	<% if permitted_to? :edit, role%>
	   <td><%= link_to 'Edit', edit_role_path(role) %></td>
	<% end %>
	<% if permitted_to? :destroy, role %>
	   <td><%= link_to 'Destroy', role, :confirm => 'Are you sure?', :method => :delete %></td>
	<% end %>
  </tr>

<% end %>
</table>

<br />

<%# permitted_to? method part of declarative_authorization %>
<% if permitted_to? :create, Role.new %>
	<%= link_to 'New Role', new_role_path %>
<% end %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<% if permitted_to? :index, @role %>
	<%= link_to 'List Roles', roles_path %>
<% end %>