config/routes.rb
Lab01PhotoAlbum::Application.routes.draw do
  resources :user_sessions
  match 'login', :to => 'user_sessions#new', :as => "login"
  match 'logout', :to => 'user_sessions#destroy', :as => "logout"

  resources :roles

  resources :users

  
    resources :albums do
	resources :photos
    end

  root :to => "albums#index"

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	
	belongs_to :album
	
	validates_presence_of :title, :location
	
end #end class Photo

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	
   #Method from declarative_authorization to identify access to 
   #functionality.  Uses config/authorization_rules.rb to know access rights.
   filter_resource_access
   
   before_filter :load_album
   
   def load_album
      @album = Album.find params[:album_id]
   end 
	
  # GET /photos
  # GET /photos.xml
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.xml
  def show
    ###Access handled through declarative_authorization's before_filter in application_controller.rb
	###@photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.xml
  def new
    ###Access handled through declarative_authorization's before_filter in application_controller.rb
	###@photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    ###Access handled through declarative_authorization's before_filter in application_controller.rb
	###@photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.xml
  def create
    ###@photo = Photo.new(params[:photo])
    ###Access handled through declarative_authorization's before_filter in application_controller.rb
	###@photo = @album.photos.build(params[:photo])

    respond_to do |format|
      if @photo.save
        ###format.html { redirect_to(@photo, :notice => 'Photo was successfully created.') }
	format.html { redirect_to([@album,@photo], :notice => 'Photo was successfully created.') }
        format.xml  { render :xml => @photo, :status => :created, :location => @photo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.xml
  def update
    ###Access handled through declarative_authorization's before_filter in application_controller.rb
	###@photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        ###format.html { redirect_to(@photo, :notice => 'Photo was successfully updated.') }
	format.html { redirect_to([@album,@photo], :notice => 'Photo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.xml
  def destroy
    ###Access handled through declarative_authorization's before_filter in application_controller.rb
	###@photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to(album_photos_url(@album)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/index.html.erb
<h1>Photos from "<%= @album.title.capitalize %>" Album</h1>

<p><i>Click image to manage photo or <%= link_to 'Add a new photo to this album', new_album_photo_path(@album) %></i></p>

<table>

<% header_row = false %>
<% @album.photos.each do |photo| %>
  <% if !header_row %>
	  <!-- tr>
	    <th></th>
	    <th>Location</th>
	    <th>Title</th>
	    <% if permitted_to? :show, photo %>
	       <th></th>
	    <% end %>
	   <% if permitted_to? :edit, photo %>
	       <th></th>
	    <% end %>
	    <% if permitted_to? :destroy, photo %>	
	       <th></th>
	    <% end %>    
	  </tr -->
	  <% header_row = true %>
  <% end %> 

  <tr>
    <td align="center">
      <!-- img src="<%= "/#{photo.location.gsub("\\","/")}" %>" width="40" height="40" / -->
      <%= link_to image_tag("/#{photo.location.gsub("\\","/")}", { :align => 'absmiddle', :border => 0, :size => '30x30', :alt => photo.title, :title => photo.title }), [@album,photo] %>
    </td>
  </tr>
  <tr>
    <td align="center" style="font-size:x-small"><%= photo.title %></td>
  </tr>
  <!-- tr>
    <td align="center">
        <% if permitted_to? :show, photo %>
    	   <%= link_to 'Show', [@album,photo] %> |
        <% end %>
        <% if permitted_to? :edit, photo %>
    	   <%= link_to 'Edit', edit_album_photo_path(@album,photo) %> |
        <% end %>
        <% if permitted_to? :destroy, photo %>	
    	   <%= link_to 'Destroy', [@album,photo], :confirm => 'Are you sure?', :method => :delete %>
        <% end %>
     </td>
  </tr -->
  
  
  
<% end %>
</table>

<br />
<% if permitted_to? :edit, @album %>
  <%= link_to 'Edit Photo Album', edit_album_path(@album) %> |
<% end %>
<% if permitted_to? :destroy, @album %>
  <%= link_to 'Destroy Photo Album', @album, :confirm => 'Are you sure?', :method => :delete %>
<% end %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>


<% if permitted_to? :show, @album %>
   <%= link_to 'View Album', album_photos_path(@album) %>
<% end %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag("/#{@photo.location.gsub("\\","/")}", { :align => 'absmiddle', :border => 0, :size => '200x200', :alt => @photo.title, :title => @photo.title }) %>
</p>

<p>
  <b>Location:</b>
  <%= @photo.location %>
</p>

<p>
  <b>Title:</b>
  <%= @photo.title %>
</p>

<% if permitted_to? :edit, @photo %>
	<%= link_to 'Edit', edit_album_photo_path(@album,@photo) %> |
<% end %>
<% if permitted_to? :destroy, @photo %>	
  <%= link_to 'Destroy', [@album, @photo], :confirm => 'Are you sure?', :method => :delete %> |
<% end %>     
<% if permitted_to? :show, @album %>
  <%= link_to 'Back to Album', album_photos_path(@album) %>
<% end %>